# I310D Homework 1
## Deadline: 11:59 pm, September 19, 2022

First, we import pandas, matplotlib, and seaborn to use as we analyze our data.
Then, we load our datasets (us_COVID_cases_and_deaths_by_state.csv and us_COVID_vaccinations_by_state.csv) into Python as a PANDAS dataframe.

In [30]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
cases_and_deaths_df = pd.read_csv('us_COVID_cases_and_deaths_by_state.csv')
cases_and_deaths_df.head()
vaccinations_df = pd.read_csv('us_COVID_vaccinations_by_state.csv')
vaccinations_df.head()

,date,state,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used,total_boosters,total_boosters_per_hundred
0,1/12/2021,AL,78134.0,377025.0,70861.0,0.15,1.59,7270.0,1.45,7.69,NaN,NaN,NaN,0.207,NaN,NaN
1,1/13/2021,AL,84040.0,378975.0,74792.0,0.19,1.71,9245.0,1.53,7.73,5906.0,5906.0,1205.0,0.222,NaN,NaN
2,1/14/2021,AL,92300.0,435350.0,80480.0,NaN,1.88,NaN,1.64,8.88,8260.0,7083.0,1445.0,0.212,NaN,NaN
3,1/15/2021,AL,100567.0,444650.0,86956.0,0.28,2.05,13488.0,1.77,9.07,8267.0,7478.0,1525.0,0.226,NaN,NaN
4,1/16/2021,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7498.0,1529.0,NaN,NaN,NaN

Now I want to clean and plot the correlation between these two data sets.
Here, I am only taking the columns I need.

In [31]:
cases_and_deaths_df_filtered = cases_and_deaths_df[['date','state', 'tot_death', 'tot_cases']]
cases_and_deaths_df_filtered.head()
vaccinations_df_filtered = vaccinations_df[['date','state', 'people_vaccinated']]
vaccinations_df_filtered.head()

        date state  people_vaccinated
0  1/12/2021    AL            70861.0
1  1/13/2021    AL            74792.0
2  1/14/2021    AL            80480.0
3  1/15/2021    AL            86956.0
4  1/16/2021    AL                NaN

For the state column, we have strings as our state descriptions. If we want to use it as an input to our model later on, it needs to be a numeric value. (1 means that the row belongs to the state and 0 means that the row doesn't)

In [38]:
cases_and_deaths_final = cases_and_deaths_df_filtered.join(pd.get_dummies(cases_and_deaths_df_filtered['state']))
cases_and_deaths_final.head()
vaccinations_final = vaccinations_df_filtered.join(pd.get_dummies(vaccinations_df_filtered['state']))
vaccinations_final.head()
# We only want to see the data for Texas
cases_final = cases_and_deaths_final[['date', 'tot_cases', 'TX']]
deaths_final = cases_and_deaths_final[['date', 'tot_death', 'TX']]
vaccinations_final = vaccinations_final[['date', 'people_vaccinated', 'TX']]

Now we can create a visualization that shows the correlation between COVID vaccination and cases/deaths in Texas

In [ ]:
# histograms!
c_TX = cases_final.loc[(cases_final.TX == 1) , 'date']
d_TX = deaths_final.loc[(deaths_final.TX == 1) , 'date']
v_TX = vaccinations_final.loc[(vaccinations_final.TX == 1) , 'date']

plt.subplot(1, 2, 1)

# density=True would normalize the distribution, but it's a little harder to see the separate categories
kwargs = dict(stacked=True, histtype='step')

plt.xlabel('date')
plt.ylabel('Number Of Individuals')
plt.title = ('COVID-19 CASES, DEATHS, AND VACCINATIONS Distribution')
plt.hist(c_TX, label='cases', color='r', **kwargs)
plt.hist(d_TX, label='deaths', color='g', **kwargs)
plt.hist(v_TX, label='vaccinations', color='b', **kwargs)

# plt.xlim(1,1100)
# plt.ylim(0,100)
plt.rcParams["figure.figsize"] = (100,60)
plt.legend()

plt.show()